# <font color='red'> *INTERMEDIATE LEVEL* </font> 
## <font color='red'> FUNCTIONS, FILTERS AND LAMBDA EXPRESSIONS  </font> 

# <font color='blue'> 1. WRITE A FUNCTION THAT TAKES A VARIABLE AND SQUARE IT, THEN TEST THE FUNCTION BY TAKING AN INPUT FROM A USER

In [33]:
# 🐍 Question 1: Write a Function that Squares a Number 🐍
# ---------------------------------------------------------
# A function is a reusable block of code designed to perform a single task.
# Functions allow us to organize code better and avoid repetition.

# Step 1: Define a function named `squared` that takes one argument `x`
# ---------------------------------------------------------
# The function will calculate the square of `x` by multiplying it by itself.
# The `return` keyword ensures the result is returned to the caller.
def squared(x):
    return x ** 2  # Returns the square of the input value

# Step 2: Get input from the user
# ---------------------------------------------------------
# The `input` function prompts the user to enter a number.
# Since input returns a string, we use `int()` to convert it to an integer.
a = int(input("Enter a number: "))

# Step 3: Test the function with the user input
# ---------------------------------------------------------
# Call the `squared` function and pass the user-provided number `a` as an argument.
# The result is formatted into a friendly message using `format()`.
# The `print` function is used to display the result.
print("The square of {} is {}".format(a, squared(a)))

# Example Run:
# ---------------------------------------------------------
# User enters: 5
# Output: "The square of 5 is 25"

# 💡 Key Notes:
# - **Function Definition**: The `def` keyword is used to define a function.
# - **Return Statement**: A function stops executing and sends the value back to the caller.
# - **Reusability**: Functions like `squared()` can be reused with any number.
# - **Input Handling**: Always ensure the input type matches the function’s expectations.

# 🌟 Something Extra:
# Let’s extend this code to handle invalid inputs gracefully using a `try-except` block.
# It ensures the program won't crash if the user enters something other than a number.



Enter a number:  16


The square of 16 is 256


In [3]:
# 🐍 Mini Project: Enhanced Square Function with Exit Option 🐍
# ---------------------------------------------------------
# 1️⃣ This project allows users to calculate the square of a number repeatedly.
# 2️⃣ If the user inputs `-1`, the program exits gracefully.
# ---------------------------------------------------------

# Define the square function
def squared(x):
    """Returns the square of a number."""
    return x ** 2

# Main loop to interact with the user
print("Welcome to the Square Calculator! 🧮 (Type -1 to exit)\n")
while True:
    try:
        # Prompt the user for a number
        a = int(input("Enter a number (or -1 to exit): "))
        
        # Check for the exit condition
        if a == -1:
            print("Thank you for using the Square Calculator. Goodbye! 👋")
            break
        
        # Calculate and display the square
        print("The square of {} is {}\n".format(a, squared(a)))
    except ValueError:
        # Handle invalid input gracefully
        print("Invalid input. Please enter an integer!\n")

# ---------------------------------------------------------
# Example Output:
# Welcome to the Square Calculator! 🧮 (Type -1 to exit)
# Enter a number (or -1 to exit): 5
# The square of 5 is 25
# Enter a number (or -1 to exit): -1
# Thank you for using the Square Calculator. Goodbye! 👋


Welcome to the Square Calculator! 🧮 (Type -1 to exit)



Enter a number (or -1 to exit):  -1


Thank you for using the Square Calculator. Goodbye! 👋


# <font color='blue'> 2. WRITE A FUNCTION THAT TAKES 2 VARIABLES FROM THE USER AND OBTAIN THE SUMMATION AND MULTIPLICATION, THEN TEST THE FUNCTION BY TAKING AN INPUT FROM A USER (REPEAT USING LAMBDA EXPRESSIONS)

In [9]:
# 🐍 Question 2: Write a Function to Calculate Sum and Multiplication 🐍
# ---------------------------------------------------------------------
# In this task, we will:
# 1️⃣ Create a function `sum_multiply` to compute both the summation and multiplication of two numbers.
# 2️⃣ Use the `return` statement to return two results simultaneously as a tuple.
# 3️⃣ Test the function with user inputs.
# 4️⃣ Rewrite the same logic using Lambda expressions for compactness and demonstrate their usage.

# Step 1: Define the function `sum_multiply`
# ---------------------------------------------------------
# This function takes two arguments, `x` and `y`.
# It calculates:
#  - Their summation (x + y)
#  - Their multiplication (x * y)
# Finally, it returns both results as a tuple.
def sum_multiply(x, y):
    summation = x + y  # Compute the sum of x and y
    multiply = x * y   # Compute the product of x and y
    return (summation, multiply)  # Return both values as a tuple

# Step 2: Take input from the user
# ---------------------------------------------------------
# Prompt the user for two integer inputs using the `input()` function.
# Convert the inputs to integers using the `int()` function.
a = int(input("Enter any integer number: "))  # First number
b = int(input("Enter another integer number: "))  # Second number

# Step 3: Call the `sum_multiply` function
# ---------------------------------------------------------
# Pass the user inputs to the function.
# Unpack the returned tuple into two variables: `result_sum` and `result_multiply`.
result_sum, result_multiply = sum_multiply(a, b)

# Step 4: Display the results
# ---------------------------------------------------------
# Use `format()` to display the sum and multiplication results in a formatted message.
print('Multiplication = {}, addition = {}'.format(result_multiply, result_sum))

# Example Run:
# ---------------------------------------------------------
# Enter any integer number: 3
# Enter another integer number: 4
# Output: "Multiplication = 12, addition = 7"

# 💡 Key Concepts Covered:
# - **Multiple Return Values**: Functions can return multiple values as a tuple.
# - **Unpacking**: Assigning each value from the tuple to a separate variable.

# ---------------------------------------------------------
# Part 2: Using Lambda Expressions
# ---------------------------------------------------------
# Lambda expressions are anonymous functions (functions without a name).
# They are used for short, one-line logic and can replace simple functions like `sum_multiply`.

# Define two Lambda expressions for summation and multiplication
summation = lambda x, y: x + y  # Lambda to compute sum
multiply = lambda x, y: x * y  # Lambda to compute multiplication

# Prompt user for input again
a = int(input("Enter any integer number: "))  # First number
b = int(input("Enter another integer number: "))  # Second number

# Use the Lambda expressions to calculate results
print('Multiplication = {}, addition = {}'.format(multiply(a, b), summation(a, b)))

# Example Run:
# ---------------------------------------------------------
# Enter any integer number: 3
# Enter another integer number: 4
# Output: "Multiplication = 12, addition = 7"

# ---------------------------------------------------------
# Advanced Example: Use Lambdas with Inline Values
# ---------------------------------------------------------
# Lambdas can be directly used with hardcoded values if user input is not required.
print('Multiplication = {}, addition = {}'.format(multiply(3, 4), summation(3, 4)))

# 📝 Summary of the Script:
# ---------------------------------------------------------
# - Created a reusable function `sum_multiply` to compute two operations simultaneously.
# - Introduced the concept of returning multiple values as a tuple and unpacking them.
# - Used Lambda expressions to simplify summation and multiplication in one-liners.
# - Demonstrated how Lambdas can replace simple named functions.

# 🚀 Project Idea:
# ---------------------------------------------------------
# Build a **Basic Calculator** app with options for addition, subtraction, multiplication, and division.
# Use Lambda expressions to implement the operations compactly.
# Include an interactive menu for the user to select operations and provide inputs dynamically.

# 🌟 What's Next?
# - Add error handling (e.g., catching division by zero).
# - Explore more complex functions, such as exponentiation and modulus, and implement them using Lambdas!

Enter any integer number:  4
Enter another integer number:  4


Multiplication = 16, addition = 8


Enter any integer number:  4
Enter another integer number:  4


Multiplication = 16, addition = 8
Multiplication = 12, addition = 7


In [7]:
# Mini Project for Question 2: Enhanced Sum and Multiply Calculator 🐍
# ---------------------------------------------------------
# 1️⃣ This project computes both summation and multiplication of two numbers.
# 2️⃣ If the user inputs `-1` for either number, the program exits gracefully.
# ---------------------------------------------------------

# Define the function to calculate summation and multiplication
def sum_multiply(x, y):
    """Returns the summation and multiplication of two numbers."""
    summation = x + y
    multiply = x * y
    return (summation, multiply)

# Main loop to interact with the user
print("Welcome to the Sum and Multiply Calculator! 🧮 (Type -1 to exit)\n")
while True:
    try:
        # Prompt the user for two numbers
        a = int(input("Enter the first integer (or -1 to exit): "))
        
        # Check for the exit condition
        if a == -1:
            print("Thank you for using the Sum and Multiply Calculator. Goodbye! 👋")
            break
        
        b = int(input("Enter the second integer (or -1 to exit): "))
        
        # Check for the exit condition
        if b == -1:
            print("Thank you for using the Sum and Multiply Calculator. Goodbye! 👋")
            break
        
        # Calculate summation and multiplication
        result_sum, result_multiply = sum_multiply(a, b)
        1
        # Display the results
        print("Multiplication = {}, Addition = {}\n".format(result_multiply, result_sum))
    except ValueError:
        # Handle invalid input gracefully
        print("Invalid input. Please enter an integer!\n")

# ---------------------------------------------------------
# Example Output:
# Welcome to the Sum and Multiply Calculator! 🧮 (Type -1 to exit)
# Enter the first integer (or -1 to exit): 3
# Enter the second integer (or -1 to exit): 4
# Multiplication = 12, Addition = 7
# Enter the first integer (or -1 to exit): -1
# Thank you for using the Sum and Multiply Calculator. Goodbye! 👋


Welcome to the Sum and Multiply Calculator! 🧮 (Type -1 to exit)



Enter the first integer (or -1 to exit):  -1


Thank you for using the Sum and Multiply Calculator. Goodbye! 👋


#  <font color='blue'>3. WRITE A FUNCTION THAT TAKES A VARIABLE AND RETURNS ITS FACTORIAL </font> 

In [15]:
# 🐍 Factorial Calculator with Exit Option 🐍
# ---------------------------------------------------------
# 1️⃣ This program calculates the factorial of a number entered by the user.
# 2️⃣ Users can repeatedly calculate factorials or exit by entering `-1`.
# 3️⃣ Includes recursion to calculate the factorial.
# ---------------------------------------------------------

# Define the factorial function
def factorial(x):
    """
    Recursive function to calculate the factorial of a number.
    A factorial of a number (n!) is the product of all positive integers from 1 to n.
    For example:
    - factorial(4) = 4 * 3 * 2 * 1 = 24
    - factorial(0) = 1 (base case)
    """
    if x == 0:
        return 1  # Base case: factorial of 0 is 1
    return x * factorial(x - 1)  # Recursive case

# Main loop to interact with the user
print("Welcome to the Factorial Calculator! 🧮 (Type -1 to exit)\n")
while True:
    try:
        # Prompt the user to input a number
        a = int(input("Enter a number to calculate its factorial (or -1 to exit): "))
        
        # Check for the exit condition
        if a == -1:
            print("Thank you for using the Factorial Calculator. Goodbye! 👋")
            break

        # Validate input to ensure it is non-negative
        if a < 0:
            print("Factorial is only defined for non-negative integers. Please try again! ❌\n")
            continue
        
        # Calculate and display the factorial
        print("The factorial of {} is {}\n".format(a, factorial(a)))
    except ValueError:
        # Handle invalid input gracefully
        print("Invalid input. Please enter an integer!\n")

# ---------------------------------------------------------
# Example Output:
# Welcome to the Factorial Calculator! 🧮 (Type -1 to exit)
# Enter a number to calculate its factorial (or -1 to exit): 4
# The factorial of 4 is 24
# Enter a number to calculate its factorial (or -1 to exit): -5
# Factorial is only defined for non-negative integers. Please try again! ❌
# Enter a number to calculate its factorial (or -1 to exit): -1
# Thank you for using the Factorial Calculator. Goodbye! 👋

# ---------------------------------------------------------
# 🚀 Additional Features to Consider:
# 1️⃣ **Iterative Approach:** Add a non-recursive version of the factorial function.
# 2️⃣ **Performance Optimization:** Include memoization to cache previously calculated results.
# 3️⃣ **Error Logging:** Create a log file to track invalid inputs or errors for debugging.
# 4️⃣ **GUI Version:** Build a graphical interface using `tkinter` or `PyQt` for user-friendly interaction.

# ---------------------------------------------------------
# 💡 Mini-Project Idea for Enhancement:
# Add a **history feature** to track all factorial calculations during the session:
# - Store inputs and outputs in a list.
# - Allow users to review all calculations made before exiting the app.

Welcome to the Factorial Calculator! 🧮 (Type -1 to exit)



Enter a number to calculate its factorial (or -1 to exit):  1


The factorial of 1 is 1



Enter a number to calculate its factorial (or -1 to exit):  4


The factorial of 4 is 24



Enter a number to calculate its factorial (or -1 to exit):  7


The factorial of 7 is 5040



Enter a number to calculate its factorial (or -1 to exit):  -1


Thank you for using the Factorial Calculator. Goodbye! 👋


# <font color='blue'> 4. DEVELOP A SCIPT WHOSE ITEMS ARE SQUARES OF THE ORIGINAL LIST </font> 

In [28]:
# 🟦 Squares of the Original List 🟦
# ------------------------------------------
# 1️⃣ This script generates a list of numbers from 1 to 20.
# 2️⃣ It calculates the square of each number in the list.
# 3️⃣ The result is a new list containing the squared values.
# ------------------------------------------

# Step 1: Create an original list of numbers using the range() function
my_list = range(1, 21)  # Numbers from 1 to 20

# Step 2: Use a list comprehension to calculate the square of each number
squared_list = [x ** 2 for x in my_list]  # Square each element in the list

# Step 3: Display the result
print("Original List:", list(my_list))  # Convert range to a list for display
print("Squared List:", squared_list)  # Print the list of squared values

# ------------------------------------------
# Example Output:
# Original List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
# Squared List: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]

# ------------------------------------------
# 🛠️ How It Works:
# - `range(1, 21)` generates numbers from 1 to 20 (inclusive).
# - The list comprehension `[x ** 2 for x in my_list]` iterates through each number in `my_list` and computes its square (`x ** 2`).
# - The result is stored in `squared_list`.

# ------------------------------------------
# 🚀 Additional Ideas for Enhancement:
# 1️⃣ **Custom Range Input:** Allow the user to define the range of numbers interactively.
# 2️⃣ **Condition-Based Squares:** Only include squares of even or odd numbers.
# 3️⃣ **Visualization:** Use a library like `matplotlib` to create a bar chart or line graph of the original vs. squared values.

# ------------------------------------------
# 💡 Mini Project: Interactive Square Calculator
def square_calculator():
    """
    Interactive application that calculates squares for a custom range of numbers.
    """
    print("🔢 Welcome to the Square Calculator App!")
    
    # Prompt the user for the range
    try:
        start = int(input("Enter the starting number of the range: "))
        end = int(input("Enter the ending number of the range: "))
        
        # Generate and calculate squares
        user_list = range(start, end + 1)  # Inclusive range
        squared_values = [x ** 2 for x in user_list]
        
        # Display results
        print("\nOriginal List:", list(user_list))
        print("Squared List:", squared_values)
    except ValueError:
        print("❌ Invalid input. Please enter valid integers!")

# Run the mini project
square_calculator()

Original List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Squared List: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]
🔢 Welcome to the Square Calculator App!


Enter the starting number of the range:  1
Enter the ending number of the range:  16



Original List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
Squared List: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256]


# <font color='blue'> 5. WRITE A FUNCTION THAT SQUARES A VARIABLE AND THEN APPLY THE FUNCTION TO A LIST OF INTEGER NUMBERS RANING FROM -20 to 20

In [31]:
# 🟦 Function to Square a Variable and Apply It to a List 🟦
# -------------------------------------------------------------------
# 1️⃣ Define a function that squares a single variable.
# 2️⃣ Generate a list of integers ranging from -20 to 20.
# 3️⃣ Use the `map()` function to apply the squaring function to the list.
# 4️⃣ Print the resulting list of squared values.
# -------------------------------------------------------------------

# Step 1: Define the function that calculates the square of a number
def squared(x):
    """
    Function to calculate the square of a given number.
    :param x: Input number (integer)
    :return: The square of the input number
    """
    return x ** 2  # Square of the number

# Step 2: Generate a range of numbers from -20 to 20
numbers = range(-20, 21)  # Includes numbers from -20 to 20

# Step 3: Apply the `squared` function to each number using `map()`
# Use the `map()` function to apply the `squared` function
numbers_squared = list(map(squared, numbers))  # Convert map object to a list

# Step 4: Display the results
print("Original Numbers:", list(numbers))  # Display the original numbers
print("Squared Numbers:", numbers_squared)  # Display the squared results

# -------------------------------------------------------------------
# Example Output:
# Original Numbers: [-20, -19, -18, ..., 0, ..., 18, 19, 20]
# Squared Numbers: [400, 361, 324, ..., 0, ..., 324, 361, 400]
# -------------------------------------------------------------------

# 🛠️ Explanation of `map()`:
# The `map()` function takes two arguments:
# 1️⃣ A function (in this case, `squared`) that defines what operation to apply.
# 2️⃣ An iterable (in this case, `numbers`), where each element is passed to the function.

# 🚀 Additional Enhancements:
# - Include a feature to filter squares of only positive or negative numbers.
# - Allow the user to enter a custom range interactively.

# -------------------------------------------------------------------
# 💡 Mini Project: Interactive Squared Range Calculator
def interactive_square_app():
    """
    Interactive application to calculate the squares of a custom range of numbers.
    """
    print("🔢 Welcome to the Squared Range Calculator!")
    print("Enter a range of numbers, and I'll calculate their squares! (Type -1 to exit)")
    
    while True:
        try:
            # Take inputs for the range
            start = int(input("Enter the starting number of the range (-1 to quit): "))
            if start == -1:
                print("👋 Thank you for using the app. Goodbye!")
                break
            
            end = int(input("Enter the ending number of the range: "))
            
            # Generate the range and calculate squares
            user_numbers = range(start, end + 1)
            squared_values = list(map(squared, user_numbers))
            
            # Display results
            print("Original Numbers:", list(user_numbers))
            print("Squared Values:", squared_values)
        except ValueError:
            print("❌ Invalid input. Please enter valid integers.")

# Run the interactive project
interactive_square_app()

Original Numbers: [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Squared Numbers: [400, 361, 324, 289, 256, 225, 196, 169, 144, 121, 100, 81, 64, 49, 36, 25, 16, 9, 4, 1, 0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]
🔢 Welcome to the Squared Range Calculator!
Enter a range of numbers, and I'll calculate their squares! (Type -1 to exit)


Enter the starting number of the range (-1 to quit):  -100
Enter the ending number of the range:  100


Original Numbers: [-100, -99, -98, -97, -96, -95, -94, -93, -92, -91, -90, -89, -88, -87, -86, -85, -84, -83, -82, -81, -80, -79, -78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66, -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
Squared Values: [10000, 9801, 9604, 9409, 9216, 9025, 8836, 8649, 8464, 8281, 8100, 7921, 7744

Enter the starting number of the range (-1 to quit):  -1


👋 Thank you for using the app. Goodbye!


# <font color='blue'> 6. WRITE 3 FUNCTIONS THAT TAKE THE RADIUS OF A CIRCLE AND RETURN THE DIAMETER, AREA AND CIRCUMFERENCE, TEST THE FUNCTION USING AN INPUT FROM A USER 

In [37]:
# 🟢 Functions to Calculate Circle Properties 🟢
# -------------------------------------------------------------------
# This script contains three functions to calculate key properties of a circle:
# 1️⃣ Diameter
# 2️⃣ Area
# 3️⃣ Circumference
# These functions take the radius as input and return the respective property.
# The script also allows the user to interactively calculate these properties.
# -------------------------------------------------------------------

# Step 1: Importing the math module
import math  # This provides access to `math.pi` for precise calculations

# Step 2: Define the function to calculate the diameter
def circle_diameter(radius):
    """
    Calculate the diameter of a circle.
    :param radius: The radius of the circle
    :return: Diameter = 2 * radius
    """
    return 2 * radius

# Step 3: Define the function to calculate the area
def circle_area(radius):
    """
    Calculate the area of a circle.
    :param radius: The radius of the circle
    :return: Area = π * radius²
    """
    return math.pi * radius**2

# Step 4: Define the function to calculate the circumference
def circle_circumference(radius):
    """
    Calculate the circumference of a circle.
    :param radius: The radius of the circle
    :return: Circumference = 2 * π * radius
    """
    return 2 * math.pi * radius

# Step 5: Interactive Application to Calculate Circle Properties
def circle_app():
    """
    An interactive app to calculate and display circle properties.
    The user can input the radius and view the results or exit by typing -1.
    """
    print("⚪ Welcome to the Circle Property Calculator! ⚪")
    print("📏 You can calculate the diameter, area, and circumference of a circle.")
    print("⛔ Enter -1 to quit the app.")
    
    while True:
        try:
            # Step 6: Get the radius from the user
            radius = float(input("Enter the radius of a circle (or type -1 to quit): "))
            
            # Exit condition
            if radius == -1:
                print("👋 Thank you for using the Circle Property Calculator. Goodbye!")
                break
            
            # Step 7: Validate the input
            if radius < 0:
                print("❌ Radius cannot be negative. Please enter a valid value.")
                continue
            
            # Step 8: Calculate and display the results
            print(f"\n📐 Circle Properties for Radius = {radius}:")
            print(f"🔹 Diameter: {circle_diameter(radius):.2f}")
            print(f"🔹 Area: {circle_area(radius):.2f}")
            print(f"🔹 Circumference: {circle_circumference(radius):.2f}\n")
        
        except ValueError:
            print("❌ Invalid input. Please enter a valid number.")

# Step 9: Run the app
circle_app()

# -------------------------------------------------------------------
# 🔵 Additional Notes:
# - The functions use `math.pi` for accurate calculations.
# - The app includes input validation to handle invalid or negative values.
# - User-friendly messages guide the interaction.
# -------------------------------------------------------------------

# 🔧 Possible Enhancements:
# 1️⃣ Add the option to calculate properties for multiple circles at once.
# 2️⃣ Include a visualization feature using a library like `matplotlib`.
# 3️⃣ Allow the user to save results to a file.
# -------------------------------------------------------------------

# 🛠 Example Interaction:
# Enter the radius of a circle: 7
# 📐 Circle Properties for Radius = 7.0:
# 🔹 Diameter: 14.00
# 🔹 Area: 153.94
# 🔹 Circumference: 43.98

# Enter the radius of a circle: -1
# 👋 Thank you for using the Circle Property Calculator. Goodbye!

⚪ Welcome to the Circle Property Calculator! ⚪
📏 You can calculate the diameter, area, and circumference of a circle.
⛔ Enter -1 to quit the app.


Enter the radius of a circle (or type -1 to quit):  7



📐 Circle Properties for Radius = 7.0:
🔹 Diameter: 14.00
🔹 Area: 153.94
🔹 Circumference: 43.98



Enter the radius of a circle (or type -1 to quit):  -1


👋 Thank you for using the Circle Property Calculator. Goodbye!


# <font color='blue'> 7. WRITE A CODE THAT TAKES A RANGE FROM A USER (UPPER AND LOWER BOUND) AND RETURNS A LIST OF POSITIVE AND EVEN NUMBERS ONLY

In [41]:
# 🟢 Filter Positive and Even Numbers from a User-Specified Range 🟢
# ------------------------------------------------------------------------------
# This program takes a range of numbers (lower and upper bounds) from the user.
# It returns a list of numbers that are BOTH:
# 1️⃣ Positive (greater than 0)
# 2️⃣ Even (divisible by 2)
# It uses the `filter()` function combined with a lambda expression for simplicity.
# ------------------------------------------------------------------------------

# Step 1: Ask the user for the range
# We ensure the lower bound must be negative to demonstrate filtering
min = int(input("Enter a number (lower bound) *must be negative* : "))  # Example: -30
max = int(input("Enter a number (Upper bound): "))  # Example: 50

# Step 2: Create a range of numbers
numbers = range(min, max)

# Step 3: Filter the numbers
# Using `filter()` with a lambda function to retain positive and even numbers
greater_than_zero = list(filter(lambda x: (x > 0 and x % 2 == 0), numbers))

# Step 4: Display the result
print("\n📋 Positive and Even Numbers from the Range:")
print(greater_than_zero)  # Example output: [2, 4, 6, 8, ..., 48]

# ------------------------------------------------------------------------------
# 🔵 Explanation:
# 1️⃣ `filter(lambda x: (x > 0 and x % 2 == 0), numbers)`
#    - Checks each number `x` in the range.
#    - `(x > 0)` ensures the number is positive.
#    - `(x % 2 == 0)` ensures the number is even.
# 2️⃣ `list()` converts the filtered object back to a list.
# ------------------------------------------------------------------------------

# 🛠 Example Interaction:
# Input:
# Enter a number (lower bound) *must be negative* : -10
# Enter a number (Upper bound): 15
#
# Output:
# 📋 Positive and Even Numbers from the Range:
# [2, 4, 6, 8, 10, 12, 14]

# ------------------------------------------------------------------------------
# 🔧 Possible Enhancements:
# 1️⃣ Add validation to ensure the lower bound is indeed negative.
# 2️⃣ Allow users to choose additional filters, such as odd numbers or multiples of 3.
# 3️⃣ Implement a function to display summary statistics like count, sum, or average.
# ------------------------------------------------------------------------------

# 🎯 Mini Project Extension:
# Let's enhance this by creating an interactive menu-based app!
def filter_numbers_app():
    """
    An interactive app to filter numbers based on user-defined criteria.
    """
    print("📊 Welcome to the Number Filter App! 📊")
    print("You can filter positive and even numbers from your specified range.")
    print("⛔ Enter -1 to quit.")
    
    while True:
        try:
            # Ask for user input
            min = int(input("\nEnter a number (lower bound) *must be negative* : "))
            if min == -1:
                print("👋 Thank you for using the Number Filter App. Goodbye!")
                break
            
            max = int(input("Enter a number (Upper bound): "))
            if max == -1:
                print("👋 Thank you for using the Number Filter App. Goodbye!")
                break
            
            # Ensure the lower bound is negative
            if min >= 0:
                print("❌ Lower bound must be negative. Please try again.")
                continue
            
            # Filter positive and even numbers
            numbers = range(min, max)
            result = list(filter(lambda x: (x > 0 and x % 2 == 0), numbers))
            
            # Display results
            print("\n📋 Positive and Even Numbers from the Range:")
            print(result)
        
        except ValueError:
            print("❌ Invalid input. Please enter valid integers.")

# Run the enhanced app
filter_numbers_app()

# ------------------------------------------------------------------------------
# 🔵 Additional Notes:
# - The mini project adds exit functionality and validation for user inputs.
# - The app ensures a user-friendly experience with clear prompts and error handling.
# ------------------------------------------------------------------------------

Enter a number (lower bound) *must be negative* :  1
Enter a number (Upper bound):  9



📋 Positive and Even Numbers from the Range:
[2, 4, 6, 8]
📊 Welcome to the Number Filter App! 📊
You can filter positive and even numbers from your specified range.
⛔ Enter -1 to quit.



Enter a number (lower bound) *must be negative* :  -1


👋 Thank you for using the Number Filter App. Goodbye!


# <font color='blue'> 8. USING FILTER AND LAMBDA EXPRESSION, WRITE A CODE THAT TAKES A LIST OF NUMBERS BELOW AND RETURNS EVEN NUMBERS ONLY

In [44]:
# 🟢 Filtering Even Numbers Using Filter and Lambda 🟢
# -----------------------------------------------------
# This script demonstrates how to use the `filter` function and a `lambda` expression
# to extract only the even numbers from a given list.
# -----------------------------------------------------

# Step 1: Create a list of numbers
numbers = [6, 17, 55, 22, 120, 59, 220, 200, 1]  # Mixed list of numbers

# Step 2: Filter even numbers
# Using filter() with a lambda function to check for even numbers.
even = list(filter(lambda x: (x % 2 == 0), numbers))

# Step 3: Display the result
print("🔢 Numbers divisible by 2 are:", even)

# -----------------------------------------------------
# Explanation of the Code:
# -----------------------------------------------------
# 1️⃣ `filter(lambda x: (x % 2 == 0), numbers)`:
#     - `filter()` applies the lambda function to each element in `numbers`.
#     - `(x % 2 == 0)` checks if a number is divisible by 2 (even).
# 2️⃣ `list()` converts the filtered object into a list.
# 3️⃣ `even` now holds all numbers from the original list that are even.
# -----------------------------------------------------

# 🛠 Example Output:
# Numbers divisible by 2 are: [6, 22, 120, 220, 200]

# -----------------------------------------------------
# 🔵 Enhancements:
# -----------------------------------------------------
# Add a user input option for dynamic filtering:
def filter_even_numbers():
    """
    A function to take a user-defined list and return even numbers from it.
    """
    print("📊 Welcome to the Even Number Filter App!")
    print("Enter numbers separated by commas (e.g., 1,2,3,4). Type -1 to exit.")
    
    while True:
        # Take user input
        user_input = input("\nEnter your list of numbers: ")
        if user_input.strip() == "-1":
            print("👋 Thank you for using the app. Goodbye!")
            break
        
        try:
            # Convert the input into a list of integers
            user_numbers = list(map(int, user_input.split(',')))
            
            # Filter even numbers
            even_numbers = list(filter(lambda x: (x % 2 == 0), user_numbers))
            
            # Display results
            print("🔢 Numbers divisible by 2 are:", even_numbers)
        
        except ValueError:
            print("❌ Invalid input. Please enter integers separated by commas.")

# Run the enhanced app
filter_even_numbers()

# -----------------------------------------------------
# 🔧 Potential Additions:
# 1️⃣ Allow filtering for different criteria, e.g., odd numbers or multiples of 5.
# 2️⃣ Provide a summary of results, such as the count and sum of even numbers.
# 3️⃣ Enable saving the filtered list to a file for further analysis.
# -----------------------------------------------------

# 🎯 Mini Project Summary:
# This app demonstrates how to dynamically filter numbers using `filter()` and `lambda`.
# It emphasizes user interaction, validation, and customization potential.

🔢 Numbers divisible by 2 are: [6, 22, 120, 220, 200]
📊 Welcome to the Even Number Filter App!
Enter numbers separated by commas (e.g., 1,2,3,4). Type -1 to exit.



Enter your list of numbers:  (1,2,3,4,5,6,7,8,9)


❌ Invalid input. Please enter integers separated by commas.



Enter your list of numbers:  1,2,3,4,5,6,7,8,9


🔢 Numbers divisible by 2 are: [2, 4, 6, 8]



Enter your list of numbers:  -1


👋 Thank you for using the app. Goodbye!


# <font color='blue'> 9. WRITE A FUNCTION THAT TAKES TWO NUMPY MATRICES AND RETURN THE ADDITION, SUBTRACTION, TRANSPOSE, PRODUCT, DOT PRODUCT

In [50]:
#🟢 Matrix Operations Using NumPy 🟢
# -----------------------------------------------------
# This script demonstrates how to perform a variety of matrix operations
# such as addition, subtraction, multiplication, transpose, and more
# using the powerful NumPy library.
# -----------------------------------------------------

# Step 1: Import the NumPy library
import numpy as np  # NumPy is essential for numerical and matrix computations.

# Step 2: Define a function for matrix operations
def matrix_operations(a, b):
    """
    Performs a variety of matrix operations on two input matrices:
    - Addition
    - Subtraction
    - Element-wise multiplication
    - Dot product
    - Transpose
    - Summation of elements row-wise and column-wise
    """
    print("🟢 Matrices Addition:\n", np.add(a, b))  # Element-wise addition
    print("\n🔵 Matrices Subtraction:\n", np.subtract(a, b))  # Element-wise subtraction
    print("\n🟢 Matrices Multiplication:\n", np.multiply(a, b))  # Element-wise multiplication
    print("\n🔵 Matrix A Transpose:\n", a.T)  # Transpose of matrix A
    print("\n🔵 Matrix B Transpose:\n", b.T)  # Transpose of matrix B
    print("\n🟢 Matrices Dot Product:\n", np.dot(a, b))  # Matrix dot product
    print("\n🔵 Square Root of Matrix A:\n", np.sqrt(a))  # Element-wise square root
    print("\n🟢 Sum of all elements in Matrix A:\n", np.sum(a))  # Sum of all elements in matrix A
    print("\n🔵 Sum of all elements in Matrix B:\n", np.sum(b))  # Sum of all elements in matrix B
    print("\n🟢 Column-wise Summation of Matrix A:\n", np.sum(a, axis=0))  # Column-wise summation
    print("\n🔵 Row-wise Summation of Matrix A:\n", np.sum(a, axis=1))  # Row-wise summation

# -----------------------------------------------------
# Step 3: Create two sample matrices
x = np.array([[1, 9], [8, 5]])  # 2x2 matrix
y = np.array([[2, 3], [7, 1]])  # 2x2 matrix

# Display the matrices for clarity
print("Matrix A:\n", x)
print("\nMatrix B:\n", y)

# Step 4: Call the matrix_operations function
matrix_operations(x, y)

# -----------------------------------------------------
# 🛠 Example Output:
# -----------------------------------------------------
# Matrix A:
# [[1 9]
#  [8 5]]

# Matrix B:
# [[2 3]
#  [7 1]]

# 🟢 Matrices Addition:
# [[ 3 12]
#  [15  6]]

# 🔵 Matrices Subtraction:
# [[-1  6]
#  [ 1  4]]

# 🟢 Matrices Multiplication:
# [[ 2 27]
#  [56  5]]

# 🔵 Matrix A Transpose:
# [[1 8]
#  [9 5]]

# 🟢 Matrices Dot Product:
# [[65 12]
#  [49 29]]
# -----------------------------------------------------

# 🔵 Suggestions for Expansion:
# -----------------------------------------------------
# 1️⃣ Accept dynamic user input for matrices to allow real-world use cases.
# 2️⃣ Save matrix results to a file (e.g., CSV or JSON).
# 3️⃣ Include operations like inverse, determinant, and rank of matrices.
# 4️⃣ Add error handling for invalid matrix operations (e.g., dot product compatibility).

# 🔵 Mini Project Add-on:
# -----------------------------------------------------
# Add a menu-driven app for matrix operations:
def matrix_app():
    """
    A menu-based matrix operations application for the user to dynamically interact with matrices.
    """
    print("📊 Welcome to the Matrix Operations App!")
    
    # Input matrices from the user
    print("\nEnter Matrix A (row by row, separated by commas):")
    a = np.array(eval(input("Matrix A (e.g., [[1, 2], [3, 4]]): ")))
    
    print("\nEnter Matrix B (row by row, separated by commas):")
    b = np.array(eval(input("Matrix B (e.g., [[5, 6], [7, 8]]): ")))

    print("\n🔧 Select an Operation:")
    print("1: Addition")
    print("2: Subtraction")
    print("3: Element-wise Multiplication")
    print("4: Dot Product")
    print("5: Transpose of Matrices")
    print("6: Exit")

    while True:
        try:
            choice = int(input("\nEnter your choice (1-6): "))
            if choice == 1:
                print("🟢 Matrices Addition:\n", np.add(a, b))
            elif choice == 2:
                print("🔵 Matrices Subtraction:\n", np.subtract(a, b))
            elif choice == 3:
                print("🟢 Element-wise Multiplication:\n", np.multiply(a, b))
            elif choice == 4:
                print("🔵 Dot Product:\n", np.dot(a, b))
            elif choice == 5:
                print("🟢 Matrix A Transpose:\n", a.T)
                print("🔵 Matrix B Transpose:\n", b.T)
            elif choice == 6:
                print("👋 Thank you for using the app. Goodbye!")
                break
            else:
                print("❌ Invalid choice. Please select a number between 1 and 6.")
        except ValueError:
            print("❌ Invalid input. Please enter a valid integer.")

# Uncomment the line below to run the app
# matrix_app()

Matrix A:
 [[1 9]
 [8 5]]

Matrix B:
 [[2 3]
 [7 1]]
🟢 Matrices Addition:
 [[ 3 12]
 [15  6]]

🔵 Matrices Subtraction:
 [[-1  6]
 [ 1  4]]

🟢 Matrices Multiplication:
 [[ 2 27]
 [56  5]]

🔵 Matrix A Transpose:
 [[1 8]
 [9 5]]

🔵 Matrix B Transpose:
 [[2 7]
 [3 1]]

🟢 Matrices Dot Product:
 [[65 12]
 [51 29]]

🔵 Square Root of Matrix A:
 [[1.         3.        ]
 [2.82842712 2.23606798]]

🟢 Sum of all elements in Matrix A:
 23

🔵 Sum of all elements in Matrix B:
 13

🟢 Column-wise Summation of Matrix A:
 [ 9 14]

🔵 Row-wise Summation of Matrix A:
 [10 13]


# <font color='blue'> 10. WRITE A FUNCTION THAT TAKES TWO VALUES FORM A USER AND SUM THEM UP. IF NO VALUES ARE PROVIDED, ASSUME DEFAULT VALUES OF 3 AND 5

In [55]:
# 🟢 Function with Default Arguments 🟢
# -----------------------------------------------------
# This function demonstrates how to use default arguments in Python.
# Default arguments are used to provide pre-defined values to function parameters.
# If the user doesn't provide any values, the function uses these defaults.
# -----------------------------------------------------

# Define a function with default parameters
def summation(x=3, y=5):
    """
    This function takes two arguments, x and y, and returns their sum.
    If no arguments are provided, it uses the default values: x=3 and y=5.
    """
    return x + y

# 🟢 Testing the Function
# -----------------------------------------------------

# 1️⃣ Case 1: Providing custom values
result_1 = summation(5, 7)  # User provides values 5 and 7
print(f"Custom input - The sum of 5 and 7 is: {result_1}")  # Output: 12

# 2️⃣ Case 2: Using default values
result_2 = summation()  # No values provided, defaults (3 and 5) will be used
print(f"Default input - The sum of 3 and 5 is: {result_2}")  # Output: 8

# -----------------------------------------------------
# 🟢 Explanation of Key Concepts
# -----------------------------------------------------
# 1️⃣ **Default Arguments**:
#    - Default arguments allow a function to have optional parameters.
#    - If the user provides values, they override the defaults.
#    - If no values are provided, the function uses the default ones.
#
# 2️⃣ **Real-World Use Cases**:
#    - Functions with default arguments are useful in scenarios where parameters 
#      often have standard or frequently used values, such as:
#      ➡️ Tax rates
#      ➡️ Interest rates in financial calculations
#      ➡️ Default user settings in applications

# 🟢 Mini Project Add-On: User Input with Default Fallback
# -----------------------------------------------------

# Enhanced version of the function to allow user input with defaults
def user_summation():
    """
    Takes input from the user for two numbers and calculates their sum.
    If no input is provided, it uses the default values of x=3 and y=5.
    """
    print("🔢 Let's calculate the sum of two numbers!")
    try:
        # Prompting user for the first number
        x = input("Enter the first number (press Enter to use default 3): ")
        x = int(x) if x else 3  # Use default 3 if input is empty

        # Prompting user for the second number
        y = input("Enter the second number (press Enter to use default 5): ")
        y = int(y) if y else 5  # Use default 5 if input is empty

        # Calculate and print the sum
        print(f"The sum of {x} and {y} is: {summation(x, y)}")  # Use the summation function
    except ValueError:
        print("❌ Invalid input! Please enter valid integers.")

# Uncomment the line below to test the enhanced version
# user_summation()

# -----------------------------------------------------
# 🟢 Potential Improvements:
# -----------------------------------------------------
# 1️⃣ Add more functionality, such as subtraction, multiplication, and division.
# 2️⃣ Extend the function to handle more than two inputs (e.g., summing a list of numbers).
# 3️⃣ Incorporate error handling for invalid inputs more robustly.
# -----------------------------------------------------

# Example Output for user_summation():
# 🔢 Let's calculate the sum of two numbers!
# Enter the first number (press Enter to use default 3): 
# Enter the second number (press Enter to use default 5): 
# The sum of 3 and 5 is: 8

Custom input - The sum of 5 and 7 is: 12
Default input - The sum of 3 and 5 is: 8


# <font color='blue'> 11. WRITE A SCRIPT THAT WILL PROMPT A USER FOR A RANGE (MIN/MAX VALUE) AND RETURNS NUMBERS THAT ARE DIVISIBLE BY 4 BUT ARE NOT MULTIPLES OF 3 

In [59]:
# 🟢 Script to Find Numbers Divisible by 4 but Not Multiples of 3 🟢
# ------------------------------------------------------------
# This script prompts the user to enter a range (minimum and maximum values).
# It identifies numbers within this range that are:
# ➡️ Divisible by 4
# ➡️ NOT multiples of 3
# ------------------------------------------------------------

# Step 1: Get input from the user for the range
# ------------------------------------------------------------
# Prompt the user to enter the minimum and maximum range values.
min_val = int(input("Enter the minimum value of the range (inclusive): "))  # Starting point of the range
max_val = int(input("Enter the maximum value of the range (exclusive): "))  # Ending point of the range

# Step 2: Initialize an empty list to store the results
# ------------------------------------------------------------
# `my_numbers` will hold numbers that satisfy the conditions.
my_numbers = []

# Step 3: Iterate through the range and apply the conditions
# ------------------------------------------------------------
for i in range(min_val, max_val):  # Loop from min_val to max_val (exclusive)
    # Check if the number is divisible by 4 but not a multiple of 3
    if (i % 4 == 0) and (i % 3 != 0):
        my_numbers.append(i)  # Add the number to the list if it satisfies the conditions

# Step 4: Display the results
# ------------------------------------------------------------
# Print the numbers that satisfy the conditions.
print("Numbers divisible by 4 but not multiples of 3:", my_numbers)

# ------------------------------------------------------------
# 🟢 Example Usage:
# ------------------------------------------------------------
# Enter the minimum value of the range (inclusive): 1
# Enter the maximum value of the range (exclusive): 50
# Numbers divisible by 4 but not multiples of 3: [4, 8, 16, 20, 28, 32, 40, 44]

# ------------------------------------------------------------
# 🟢 Explanation of Key Concepts:
# ------------------------------------------------------------
# 1️⃣ **Divisibility Check**:
#    - A number is divisible by another if the remainder of the division is 0.
#      ➡️ Example: `8 % 4 == 0` (8 is divisible by 4).
#
# 2️⃣ **Logical Conditions**:
#    - `(i % 4 == 0)` checks if `i` is divisible by 4.
#    - `(i % 3 != 0)` ensures `i` is NOT a multiple of 3.
#    - Both conditions are combined using the logical AND operator (`and`).

# ------------------------------------------------------------
# 🟢 Possible Improvements:
# ------------------------------------------------------------
# 1️⃣ Add a feature to check for additional conditions (e.g., divisibility by 5, prime numbers).
# 2️⃣ Allow the user to specify custom divisibility and exclusion rules.
# 3️⃣ Visualize the results in a chart or graph for better understanding.

# ------------------------------------------------------------
# 🟢 Mini Project Idea:
# ------------------------------------------------------------
# Extend this script into a **Divisibility Checker App**:
# ➡️ User specifies the conditions (e.g., divisible by 4 and not by 3).
# ➡️ App returns results along with statistics (e.g., count of matching numbers).
# ➡️ Add the option to save the results to a file for future reference.

Enter the minimum value of the range (inclusive):  4
Enter the maximum value of the range (exclusive):  44


Numbers divisible by 4 but not multiples of 3: [4, 8, 16, 20, 28, 32, 40]


# <font color='blue'> 12. DEFINE AN ENGLISH TO FRENCH TRANSLATOR FUNCTION THAT TAKES AN INPUT FROM A USER AND RETURNS THE TRANSLATION, USE ANY 5 KNOWN WORDS

In [64]:
# 🟢 English to French Translator Function 🟢
# ------------------------------------------------------------
# This script implements a simple English-to-French translator.
# ➡️ A dictionary is used to store translations for predefined words.
# ➡️ The program prompts the user to input an English word and returns
#    its French translation if available.
# ➡️ If the word is not found, an appropriate message is displayed.
# ------------------------------------------------------------

# Step 1: Define a dictionary of English-to-French translations
# ------------------------------------------------------------
# The dictionary `eng_french` contains English words as keys and their
# French translations as values.
eng_french = {
    'happy': 'heureux',            # Example: "happy" translates to "heureux"
    'success': 'Succès',           # Example: "success" translates to "Succès"
    'studying': "en train d'étudier",  # Example: "studying" translates to "en train d'étudier"
    'traveling': 'en voyageant',   # Example: "traveling" translates to "en voyageant"
    'love': 'amour'                # Example: "love" translates to "amour"
}

# Step 2: Define the translation function
# ------------------------------------------------------------
# The function takes an English word as input and looks it up in the dictionary.
def dictionary_English2French(word):
    """
    Translate an English word into French using a predefined dictionary.

    Args:
        word (str): The English word to translate.
    
    Returns:
        str: The French translation, or an error message if not found.
    """
    try:
        # Try to fetch the word from the dictionary
        return eng_french[word]
    except KeyError:
        # If the word is not found, return an error message
        return "⚠️ The dictionary does not contain this word."

# Step 3: Prompt the user for input and return the translation
# ------------------------------------------------------------
# Ask the user to enter an English word.
# `.lower()` ensures case insensitivity by converting the input to lowercase.
word = input("🔤 Enter an English word to translate: ").lower()

# Print the translated word or the error message.
print(f"French translation: {dictionary_English2French(word)}")

# ------------------------------------------------------------
# 🟢 Example Usage:
# ------------------------------------------------------------
# 🔤 Enter an English word to translate: HAPPY
# French translation: heureux
# 
# 🔤 Enter an English word to translate: SUCCESS
# French translation: Succès
# 
# 🔤 Enter an English word to translate: UNKNOWN
# French translation: ⚠️ The dictionary does not contain this word.

# ------------------------------------------------------------
# 🟢 Explanation of Key Concepts:
# ------------------------------------------------------------
# 1️⃣ **Dictionaries in Python**:
#    - A dictionary is a collection of key-value pairs.
#    - Here, the English word is the key, and its French translation is the value.
#
# 2️⃣ **Exception Handling**:
#    - We use a `try-except` block to handle cases where the input word is not in the dictionary.
#    - If a `KeyError` occurs (word not found), we return an error message.

# ------------------------------------------------------------
# 🟢 Ideas for Improvements:
# ------------------------------------------------------------
# 1️⃣ Add support for translating phrases instead of single words.
# 2️⃣ Allow users to add new words to the dictionary dynamically.
#    ➡️ Example: User can input both an English word and its French translation.
# 3️⃣ Use an external database or API for translations to support larger vocabularies.
# 4️⃣ Provide reverse translation (French-to-English).

# ------------------------------------------------------------
# 🟢 Fun Fact:
# ------------------------------------------------------------
# The word "amour" (French for "love") is one of the most borrowed words from French into other languages! 🥰

🔤 Enter an English word to translate:  love


French translation: amour


# NOW YOU SHOULD BE FAMILIAR WITH FUNCTIONS, GREAT JOB!