# PYTHON PROGRAMMING FUNDAMENTALS - PART B


This Notebook will cover the following topics:    
- Numpy basics
- Built-in methods and functions 
- Obtain shape, length and type of Numpy arrays
- Reshape 
- Minimum and maximum and their indices
- Mathematical Operations
- Indexing and slicing 
- Selection 



# NUMPY BASICS
- NumPy is a Linear Algebra Library used for multidimensional arrays
- Installation: Use the command window, type: conda install numpy

In [3]:
# NUMPY BASICS 🌟

# 🧠 **What is NumPy?**
# NumPy (Numerical Python) is a powerful library for numerical computing in Python. 
# It is widely used for working with arrays, performing mathematical operations, 
# and it serves as the foundation for libraries like Pandas, TensorFlow, and SciPy.

# -----------------------------------------------
# ✨ **Key Features of NumPy Arrays**
# -----------------------------------------------
# 1. **Homogeneous Data:** All elements in a NumPy array must be of the same data type.
# 2. **Speed:** Operations on NumPy arrays are faster compared to Python lists.
# 3. **Memory Efficiency:** NumPy uses less memory than native Python lists.
# 4. **Multidimensional Support:** Easily create and manipulate arrays with 1D, 2D, and even higher dimensions.
# 5. **Broadcasting:** Perform arithmetic operations directly on arrays without explicit loops.
# 6. **Rich Ecosystem:** NumPy integrates seamlessly with other scientific libraries.

# -----------------------------------------------
# 🚀 **Step 1: Installing and Importing NumPy**
# -----------------------------------------------

# Import NumPy library
import numpy as np
print("✅ NumPy imported successfully!")

# If NumPy isn't installed, use the following command in the terminal:
# pip install numpy (or conda install numpy if using Anaconda)

# -----------------------------------------------
# 🚀 **Step 2: Creating NumPy Arrays**
# -----------------------------------------------

# 💡 **1D Array (One-dimensional)**
# Let's create a Python list and convert it to a NumPy array.
my_list = [5, 3, 10]  # Python list
array_1d = np.array(my_list)  # Convert list to NumPy array

print("🟢 Python List:", my_list)
print("🔵 NumPy Array:", array_1d)
print("Type:", type(array_1d))  # numpy.ndarray

# ✨ **Key Difference:** NumPy arrays allow element-wise operations. 
# For example, let's add 2 to every element in the array:
print("\n🔹 Element-wise operation:")
print("Array + 2:", array_1d + 2)

# 💡 **2D Array (Two-dimensional)**
# A 2D array can be thought of as a matrix.
array_2d = np.array([[1, 2, 3], [4, 5, 6]])  # Define a 2D array
print("\n🟢 2D Array (Matrix):\n", array_2d)

# 💡 **3D Array (Three-dimensional)**
# A 3D array can be visualized as a collection of 2D matrices stacked together.
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n🟢 3D Array:\n", array_3d)

# -----------------------------------------------
# 🚀 **Step 3: Generating Arrays Automatically**
# -----------------------------------------------

# NumPy provides built-in methods to create arrays more efficiently.

# 1. Array of Zeros:
zeros_array = np.zeros((3, 4))  # A 3x4 array filled with zeros
print("\n🔵 Array of Zeros:\n", zeros_array)

# 2. Array of Ones:
ones_array = np.ones((2, 5))  # A 2x5 array filled with ones
print("\n🔵 Array of Ones:\n", ones_array)

# 3. Array of a Range of Numbers:
range_array = np.arange(0, 10, 2)  # Start=0, Stop=10 (exclusive), Step=2
print("\n🔵 Range Array (arange):", range_array)

# 4. Linearly Spaced Values:
linspace_array = np.linspace(0, 1, 5)  # 5 values evenly spaced between 0 and 1
print("\n🔵 Linearly Spaced Values (linspace):", linspace_array)

# 5. Random Array:
random_array = np.random.random((2, 3))  # Random values [0, 1) in a 2x3 array
print("\n🔵 Random Array:\n", random_array)

# 🎯 **Try This:** Use `np.random.randint(start, stop, size)` to create an array of random integers.

# -----------------------------------------------
# 🚀 **Step 4: Array Attributes**
# -----------------------------------------------

# Check attributes of an array:
print("\n🔎 Array Attributes:")
print("Shape of 2D array:", array_2d.shape)  # Returns (rows, columns)
print("Data Type:", array_2d.dtype)  # Returns the data type of the array elements
print("Number of Dimensions (ndim):", array_2d.ndim)  # 2D -> 2

# -----------------------------------------------
# 🏆 **Summary**
# -----------------------------------------------

# ✅ NumPy arrays are faster, more memory-efficient, and support element-wise operations.
# ✅ You can create 1D, 2D, 3D, and higher-dimensional arrays easily.
# ✅ NumPy provides functions like zeros, ones, arange, linspace, and random for quick array creation.

# -----------------------------------------------
# 🏋️‍♂️ **Practice Exercises**
# -----------------------------------------------

# 1️⃣ Create a 5x5 matrix filled with random integers between 1 and 100.
# 2️⃣ Generate an array of 10 equally spaced values between -5 and 5.
# 3️⃣ Check the data type and shape of your created arrays.

# -----------------------------------------------
# 🎁 **Extra: Broadcasting Example**
# -----------------------------------------------

# Broadcasting allows you to perform operations between arrays of different shapes.
# Example: Adding a 1D array to each row of a 2D array.

matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

print("\n🔵 Broadcasting Example:")
print("Matrix:\n", matrix)
print("Vector:", vector)
print("Matrix + Vector:\n", matrix + vector)

✅ NumPy imported successfully!
🟢 Python List: [5, 3, 10]
🔵 NumPy Array: [ 5  3 10]
Type: <class 'numpy.ndarray'>

🔹 Element-wise operation:
Array + 2: [ 7  5 12]

🟢 2D Array (Matrix):
 [[1 2 3]
 [4 5 6]]

🟢 3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

🔵 Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

🔵 Array of Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

🔵 Range Array (arange): [0 2 4 6 8]

🔵 Linearly Spaced Values (linspace): [0.   0.25 0.5  0.75 1.  ]

🔵 Random Array:
 [[0.58064273 0.15632754 0.31493038]
 [0.11939033 0.06462466 0.12295724]]

🔎 Array Attributes:
Shape of 2D array: (2, 3)
Data Type: int32
Number of Dimensions (ndim): 2

🔵 Broadcasting Example:
Matrix:
 [[1 2 3]
 [4 5 6]]
Vector: [10 20 30]
Matrix + Vector:
 [[11 22 33]
 [14 25 36]]


# BUILT-IN METHODS AND FUNCTIONS

In [6]:
# BUILT-IN METHODS AND FUNCTIONS 📚

# 🧠 **What are NumPy Built-in Methods?**
# NumPy provides numerous methods and functions to create, manipulate, and perform operations on arrays.
# These built-in methods make operations more efficient and less error-prone compared to manual loops.

# -----------------------------------------------
# 🚀 **Random Number Generation**
# -----------------------------------------------

# 1️⃣ **np.random.rand()**
# This generates an array of random numbers uniformly distributed between 0 and 1.
# Syntax: np.random.rand(dim1, dim2, ...)
# Generates random numbers in a specific shape.
random_uniform = np.random.rand(3, 4)  # 3x4 array
print("\n🔹 Random Uniform Array (0 to 1):\n", random_uniform)

# 2️⃣ **np.random.randn()**
# Generates samples from a standard normal distribution (mean=0, std=1).
# Useful for simulations or initializing weights in machine learning.
random_normal = np.random.randn(2, 5)  # 2x5 array
print("\n🔹 Random Normal Array (Mean 0, Std 1):\n", random_normal)

# 3️⃣ **np.random.randint()**
# Generates random integers between a lower bound (inclusive) and an upper bound (exclusive).
# Syntax: np.random.randint(lower, upper, size)
random_integers = np.random.randint(10, 50, (3, 3))  # 3x3 array of integers between 10 and 50
print("\n🔹 Random Integers:\n", random_integers)

# -----------------------------------------------
# 🚀 **Array Manipulation**
# -----------------------------------------------

# 1️⃣ **np.arange()**
# Similar to Python's range(), but it creates a NumPy array instead of a list.
# Syntax: np.arange(start, stop, step)
arange_array = np.arange(0, 20, 3)  # Numbers from 0 to 20 with a step of 3
print("\n🔹 Array with np.arange:\n", arange_array)

# 2️⃣ **np.linspace()**
# Creates an array of evenly spaced numbers over a specified range.
# Syntax: np.linspace(start, stop, num_elements)
linspace_array = np.linspace(0, 1, 5)  # 5 values between 0 and 1
print("\n🔹 Array with np.linspace:\n", linspace_array)

# -----------------------------------------------
# 🚀 **Mathematical Operations**
# -----------------------------------------------

# 1️⃣ **np.max() and np.min()**
# Finds the maximum and minimum values in an array.
array_math = np.array([3, 6, 9, 12, 15])
print("\n🔹 Maximum Value:", np.max(array_math))  # 15
print("🔹 Minimum Value:", np.min(array_math))  # 3

# 2️⃣ **np.argmax() and np.argmin()**
# Returns the index of the maximum and minimum values.
print("\n🔹 Index of Maximum Value:", np.argmax(array_math))  # 4
print("🔹 Index of Minimum Value:", np.argmin(array_math))  # 0

# 3️⃣ **np.sum() and np.mean()**
# Computes the sum and mean of array elements.
print("\n🔹 Sum of Array:", np.sum(array_math))  # 45
print("🔹 Mean of Array:", np.mean(array_math))  # 9.0

# 4️⃣ **np.std() and np.var()**
# Computes the standard deviation and variance of the array.
print("\n🔹 Standard Deviation:", np.std(array_math))  # 4.2426...
print("🔹 Variance:", np.var(array_math))  # 18.0

# -----------------------------------------------
# 🚀 **Sorting and Reshaping Arrays**
# -----------------------------------------------

# 1️⃣ **np.sort()**
# Returns a sorted copy of the array.
unsorted_array = np.array([12, 7, 19, 3, 5])
sorted_array = np.sort(unsorted_array)
print("\n🔹 Original Array:", unsorted_array)
print("🔹 Sorted Array:", sorted_array)

# 2️⃣ **np.reshape()**
# Changes the shape of an array without changing its data.
array_reshaped = np.arange(1, 13).reshape(3, 4)  # Converts a 1D array into a 3x4 array
print("\n🔹 Reshaped Array (3x4):\n", array_reshaped)

# 3️⃣ **np.flatten()**
# Converts a multi-dimensional array into a 1D array.
flattened_array = array_reshaped.flatten()
print("\n🔹 Flattened Array:", flattened_array)

# -----------------------------------------------
# 🎁 **Extra: Random Sampling from Arrays**
# -----------------------------------------------

# 1️⃣ **np.random.choice()**
# Randomly selects elements from an array, with or without replacement.
original_array = np.array([1, 2, 3, 4, 5, 6])
random_sample = np.random.choice(original_array, size=3, replace=False)
print("\n🔹 Random Sample (Without Replacement):", random_sample)

# -----------------------------------------------
# 🏆 **Summary**
# -----------------------------------------------

# ✅ NumPy provides powerful methods for generating random numbers, performing operations, 
#    and manipulating arrays.
# ✅ Useful methods like np.sort, np.reshape, np.flatten, and statistical functions 
#    make working with data much easier.

# -----------------------------------------------
# 🏋️‍♂️ **Practice Exercises**
# -----------------------------------------------

# 1️⃣ Create a 4x4 matrix of random integers between 0 and 100.
# 2️⃣ Use np.linspace() to generate 7 evenly spaced values between -5 and 5.
# 3️⃣ Find the index of the maximum value in a 2D array created using np.random.randint().



🔹 Random Uniform Array (0 to 1):
 [[0.74604185 0.14136301 0.31770614 0.48621922]
 [0.12613962 0.50850561 0.39963998 0.03145157]
 [0.60925037 0.53992772 0.22454028 0.07522538]]

🔹 Random Normal Array (Mean 0, Std 1):
 [[ 1.99005059  0.00552839 -0.43753194 -0.36961502 -0.4920746 ]
 [-1.02777998 -0.85908946  0.28543017 -0.74693949 -0.07475123]]

🔹 Random Integers:
 [[48 17 46]
 [41 31 12]
 [42 42 37]]

🔹 Array with np.arange:
 [ 0  3  6  9 12 15 18]

🔹 Array with np.linspace:
 [0.   0.25 0.5  0.75 1.  ]

🔹 Maximum Value: 15
🔹 Minimum Value: 3

🔹 Index of Maximum Value: 4
🔹 Index of Minimum Value: 0

🔹 Sum of Array: 45
🔹 Mean of Array: 9.0

🔹 Standard Deviation: 4.242640687119285
🔹 Variance: 18.0

🔹 Original Array: [12  7 19  3  5]
🔹 Sorted Array: [ 3  5  7 12 19]

🔹 Reshaped Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

🔹 Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

🔹 Random Sample (Without Replacement): [6 1 3]


# SHAPE, LENGTH AND TYPE OF NUMPY ARRAYS

In [9]:
# SHAPE, LENGTH, AND TYPE OF NUMPY ARRAYS 📏🔢

# 🧠 **Understanding Shape, Length, and Type of Arrays**
# NumPy arrays have attributes that help us understand their structure:
# 1️⃣ `len(array)` gives the number of elements along the first dimension (rows).
# 2️⃣ `.shape` provides the dimensions (rows, columns, etc.) of the array.
# 3️⃣ `.dtype` specifies the data type of the elements in the array.

# -----------------------------------------------
# 🚀 **Length of an Array**
# -----------------------------------------------
# Example 1: Getting the length of a 1D array.
# `len()` is equivalent to the number of elements in the first axis (rows in a 2D array).
y = np.array([10, 20, 30])
print("🔹 Length of array y:", len(y))  # Output: 3 (3 elements in total)

# -----------------------------------------------
# 🚀 **Shape of an Array**
# -----------------------------------------------
# `.shape` returns a tuple representing the dimensions of the array.

# Example 2: 1D Array
# Here, `.shape` shows `(3,)`, which means the array has 3 elements and is 1-dimensional.
print("🔹 Shape of array y:", y.shape)  # Output: (3,)

# Example 3: 2D Array
# For a 2D array, `.shape` returns the number of rows and columns as `(rows, columns)`.
matrix = np.array([[1, 2], [3, 4]])  # A 2x2 matrix
print("\n🔹 2D Matrix:\n", matrix)
print("🔹 Shape of the matrix:", matrix.shape)  # Output: (2, 2)

# Example 4: Higher-Dimensional Arrays
# For 3D or higher-dimensional arrays, `.shape` provides all dimensions.
tensor = np.random.randint(0, 10, (2, 3, 4))  # A 3D array with shape (2, 3, 4)
print("\n🔹 3D Tensor Shape:", tensor.shape)  # Output: (2, 3, 4)

# -----------------------------------------------
# 🚀 **Data Type of Elements**
# -----------------------------------------------
# `.dtype` reveals the type of elements stored in the array (e.g., int32, float64).

# Example 5: Checking Data Type
# Creating an integer array.
int_array = np.array([1, 2, 3])
print("\n🔹 Data Type of int_array:", int_array.dtype)  # Output: int32 or int64 (depends on system)

# Example 6: Floating-Point Array
float_array = np.array([1.0, 2.0, 3.5])
print("🔹 Data Type of float_array:", float_array.dtype)  # Output: float64

# Example 7: Mixed-Type Input
# NumPy converts all elements to the same type (type coercion).
mixed_array = np.array([1, 2.5, 3])
print("🔹 Data Type of mixed_array:", mixed_array.dtype)  # Output: float64

# -----------------------------------------------
# 🎁 **Additional Insights**
# -----------------------------------------------

# ➡️ Why is `.shape` Important? 🧐
# `.shape` helps us understand the structure of an array, which is crucial when performing
# matrix operations, reshaping, or broadcasting.

# ➡️ Why Check `.dtype`? 🛠️
# Knowing `.dtype` ensures that your computations are accurate and memory-efficient.
# For example:
# - Using `float32` consumes less memory than `float64` but may reduce precision.
# - Integer types like `int8` are memory-efficient for small numbers.

# ➡️ Bonus: Change Data Type 🌀
# Use `.astype()` to change the data type of an array.
converted_array = mixed_array.astype(int)  # Convert float64 to int
print("\n🔹 Converted Array (int):", converted_array)

# -----------------------------------------------
# 🏆 **Summary**
# -----------------------------------------------
# ✅ `len()` gives the number of elements along the first dimension (rows).
# ✅ `.shape` reveals the dimensions of an array (rows, columns, etc.).
# ✅ `.dtype` specifies the data type of array elements (e.g., int, float).
# ✅ Understanding these attributes is vital for debugging, optimizing, and performing mathematical operations.

# -----------------------------------------------
# 🏋️‍♂️ **Practice Exercises**
# -----------------------------------------------

# 1️⃣ Create a 4x3 matrix of random integers and print its shape and data type.
# 2️⃣ Check the `.shape` and `.dtype` of a 3D tensor created using np.random.randn().
# 3️⃣ Convert a float array to an integer array using `.astype()` and observe the difference.


🔹 Length of array y: 3
🔹 Shape of array y: (3,)

🔹 2D Matrix:
 [[1 2]
 [3 4]]
🔹 Shape of the matrix: (2, 2)

🔹 3D Tensor Shape: (2, 3, 4)

🔹 Data Type of int_array: int32
🔹 Data Type of float_array: float64
🔹 Data Type of mixed_array: float64

🔹 Converted Array (int): [1 2 3]


# RESHAPE

In [27]:
# RESHAPE OPERATION 🔄

# 🧠 **What is Reshape?**
# Reshaping allows you to change the shape (dimensions) of an array without changing its data.
# The total number of elements must remain the same.
# For example:
#   - A 1D array with 6 elements can be reshaped into a 2D array with 2 rows and 3 columns.
#   - Similarly, a 2D array can be reshaped into a 3D array if dimensions are compatible.

# -----------------------------------------------
# 🚀 **Basic Reshape Example**
# -----------------------------------------------
# Let's create a simple 1D array and reshape it into a 2D array.

import numpy as np

# Creating a 1D array
y = np.array([3, 5, 7, 8])  # A 1D array with 4 elements
print("🔹 Original Array:\n", y)  # Output: [3 5 7 8]

# Reshaping into a 2D array (2 rows, 2 columns)
reshaped_y = y.reshape(2, 2)
print("\n🔹 Reshaped Array:\n", reshaped_y)
# Output:
# [[3 5]
#  [7 8]]

# -----------------------------------------------
# 🚀 **Rules for Reshaping**
# -----------------------------------------------
# 1️⃣ The product of dimensions in `.reshape()` must match the number of elements in the array.
#    Example: A 1D array with 6 elements can be reshaped into (2, 3), (3, 2), or (6, 1), but not (2, 2).
# 2️⃣ If the dimensions are incompatible, NumPy will raise a `ValueError`.

# Example: Incompatible reshaping
try:
    y.reshape(3, 3)  # This will raise an error
except ValueError as e:
    print("\n⚠️ Reshape Error:", e)

# -----------------------------------------------
# 🚀 **Using -1 in Reshape**
# -----------------------------------------------
# The `-1` dimension tells NumPy to infer the size automatically based on the remaining dimensions.
# This is particularly useful when only one dimension is unknown.

# Example: Using -1 to automatically determine the shape
z = np.array([1, 2, 3, 4, 5, 6])
reshaped_z = z.reshape(2, -1)  # NumPy calculates the number of columns (6 / 2 = 3)
print("\n🔹 Reshaped with -1:\n", reshaped_z)
# Output:
# [[1 2 3]
#  [4 5 6]]

# -----------------------------------------------
# 🚀 **Flattening Arrays**
# -----------------------------------------------
# `.reshape(-1)` can also be used to flatten a multidimensional array into a 1D array.

# Example: Flattening a 2D array
flattened = reshaped_y.reshape(-1)
print("\n🔹 Flattened Array:\n", flattened)  # Output: [3 5 7 8]

# -----------------------------------------------
# 🚀 **Reshaping Higher-Dimensional Arrays**
# -----------------------------------------------
# Reshape can handle arrays of any dimension. Here's an example with a 3D array.

# Creating a 3D array
tensor = np.arange(1, 25).reshape(2, 3, 4)  # Shape: (2 blocks, 3 rows, 4 columns)
print("\n🔹 3D Array:\n", tensor)
# Output:
# [[[ 1  2  3  4]
#   [ 5  6  7  8]
#   [ 9 10 11 12]]
#
#  [[13 14 15 16]
#   [17 18 19 20]
#   [21 22 23 24]]]

# Reshaping into a 2D array
reshaped_tensor = tensor.reshape(6, 4)  # 6 rows, 4 columns
print("\n🔹 Reshaped 3D -> 2D:\n", reshaped_tensor)
# Output:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  ...
#  [21 22 23 24]]

# -----------------------------------------------
# 🏆 **Summary**
# -----------------------------------------------
# ✅ Reshaping changes the structure of an array without modifying its data.
# ✅ Total number of elements must remain constant when reshaping.
# ✅ `-1` can be used to automatically infer one dimension.
# ✅ Reshaping is crucial for preparing data for machine learning models or mathematical operations.

# -----------------------------------------------
# 🏋️‍♂️ **Practice Exercises**
# -----------------------------------------------
# 1️⃣ Create a 1D array with 12 elements and reshape it into:
#     - A 2D array with 3 rows and 4 columns.
#     - A 3D array with shape (2, 2, 3).
# 2️⃣ Flatten a 2D array into a 1D array using `.reshape(-1)`.
# 3️⃣ Create a 3D tensor and experiment with reshaping it into a 2D array.


🔹 Original Array:
 [3 5 7 8]

🔹 Reshaped Array:
 [[3 5]
 [7 8]]

⚠️ Reshape Error: cannot reshape array of size 4 into shape (3,3)

🔹 Reshaped with -1:
 [[1 2 3]
 [4 5 6]]

🔹 Flattened Array:
 [3 5 7 8]

🔹 3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

🔹 Reshaped 3D -> 2D:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


# MAX AND MIN VALUES AND THEIR INDEX

In [16]:
# MAX AND MIN VALUES AND THEIR INDEX 📈📉

# 🧠 **What are max() and min()?**
# - `.max()` is used to find the largest value in a NumPy array.
# - `.min()` is used to find the smallest value in a NumPy array.
# - `argmax()` and `argmin()` give the **index** of the maximum and minimum values respectively.

# -----------------------------------------------
# 🚀 **Example: Basic Max and Min Operations**
# -----------------------------------------------
import numpy as np

# Create an array
y = np.array([3, 5, 7, 8])  # A simple 1D array
print("🔹 Array y:", y)

# Find the maximum value
max_value = y.max()
print("\n🔹 Maximum Value:", max_value)  # Output: 8

# Find the minimum value
min_value = y.min()
print("🔹 Minimum Value:", min_value)  # Output: 3

# -----------------------------------------------
# 🚀 **Finding Indices of Max and Min Values**
# -----------------------------------------------
# - Use `.argmax()` to find the index of the largest value.
# - Use `.argmin()` to find the index of the smallest value.

# Index of maximum value
max_index = y.argmax()
print("\n🔹 Index of Maximum Value:", max_index)  # Output: 3

# Index of minimum value
min_index = y.argmin()
print("🔹 Index of Minimum Value:", min_index)  # Output: 0

# -----------------------------------------------
# 🚀 **Working with Multidimensional Arrays**
# -----------------------------------------------
# Let's explore how `max()`, `min()`, and their indices work in a 2D array.

# Create a 2D array
matrix = np.array([[1, 8, 3],
                   [7, 2, 6]])
print("\n🔹 2D Array:\n", matrix)

# Maximum value in the entire matrix
matrix_max = matrix.max()
print("\n🔹 Maximum Value (2D):", matrix_max)  # Output: 8

# Minimum value in the entire matrix
matrix_min = matrix.min()
print("🔹 Minimum Value (2D):", matrix_min)  # Output: 1

# Maximum value along rows (axis=1)
row_max = matrix.max(axis=1)
print("\n🔹 Maximum Value Along Rows:", row_max)  # Output: [8 7]

# Minimum value along columns (axis=0)
col_min = matrix.min(axis=0)
print("🔹 Minimum Value Along Columns:", col_min)  # Output: [1 2 3]

# Index of maximum value along rows
row_max_indices = matrix.argmax(axis=1)
print("\n🔹 Index of Maximum Value Along Rows:", row_max_indices)  # Output: [1 0]

# Index of minimum value along columns
col_min_indices = matrix.argmin(axis=0)
print("🔹 Index of Minimum Value Along Columns:", col_min_indices)  # Output: [0 1 0]

# -----------------------------------------------
# 🏆 **Summary**
# -----------------------------------------------
# ✅ `.max()` and `.min()` are used to find the largest and smallest values in an array.
# ✅ `.argmax()` and `.argmin()` return the indices of the maximum and minimum values.
# ✅ These functions are extremely useful in data analysis, where identifying extrema is crucial.
# ✅ Multidimensional arrays can specify `axis` to find extrema row-wise or column-wise.

# -----------------------------------------------
# 🏋️‍♂️ **Practice Exercises**
# -----------------------------------------------
# 1️⃣ Create a 1D array of random integers and find:
#     - The maximum and minimum values.
#     - Their indices using `argmax()` and `argmin()`.
# 2️⃣ For a 3x3 matrix, find:
#     - Row-wise maxima and their indices.
#     - Column-wise minima and their indices.

# 🚀 Example Starter Code:
practice_array = np.random.randint(1, 100, size=10)  # Random integers from 1 to 100
print("\n🔹 Practice Array:", practice_array)
print("🔹 Max Value:", practice_array.max())
print("🔹 Min Value:", practice_array.min())
print("🔹 Index of Max Value:", practice_array.argmax())
print("🔹 Index of Min Value:", practice_array.argmin())


🔹 Array y: [3 5 7 8]

🔹 Maximum Value: 8
🔹 Minimum Value: 3

🔹 Index of Maximum Value: 3
🔹 Index of Minimum Value: 0

🔹 2D Array:
 [[1 8 3]
 [7 2 6]]

🔹 Maximum Value (2D): 8
🔹 Minimum Value (2D): 1

🔹 Maximum Value Along Rows: [8 7]
🔹 Minimum Value Along Columns: [1 2 3]

🔹 Index of Maximum Value Along Rows: [1 0]
🔹 Index of Minimum Value Along Columns: [0 1 0]

🔹 Practice Array: [62 85 25 27 95 58 86 20 71 15]
🔹 Max Value: 95
🔹 Min Value: 15
🔹 Index of Max Value: 4
🔹 Index of Min Value: 9


# MATHEMATICAL OPERATIONS

In [19]:
# MATHEMATICAL OPERATIONS 🧮
# NumPy provides fast and efficient ways to perform mathematical operations on arrays.
# These operations are applied element-wise by default. Let's explore! 🚀

import numpy as np

# -----------------------------------------------
# 🚀 **Create Arrays for Operations**
# -----------------------------------------------
x = np.arange(1, 5)  # Create an array with elements [1, 2, 3, 4]
y = np.arange(1, 5)  # Another array with the same values
print("🔹 Array x:", x)
print("🔹 Array y:", y)

# -----------------------------------------------
# 🚀 **Addition of Arrays**
# -----------------------------------------------
# Adding two arrays will add their elements element-wise.
z = x + y
print("\n🔹 Addition (x + y):", z)  # [2, 4, 6, 8]

# -----------------------------------------------
# 🚀 **Subtraction, Multiplication, and Division**
# -----------------------------------------------
# Element-wise subtraction
z_sub = x - y
print("\n🔹 Subtraction (x - y):", z_sub)  # [0, 0, 0, 0]

# Element-wise multiplication
z_mul = x * y
print("🔹 Multiplication (x * y):", z_mul)  # [1, 4, 9, 16]

# Element-wise division
z_div = x / y
print("🔹 Division (x / y):", z_div)  # [1.0, 1.0, 1.0, 1.0]

# -----------------------------------------------
# 🚀 **Exponentiation and Square Roots**
# -----------------------------------------------
# Square of each element in x
z_square = x ** 2
print("\n🔹 Squared (x ** 2):", z_square)  # [1, 4, 9, 16]

# Square root of each element in z_square
z_sqrt = np.sqrt(z_square)
print("🔹 Square Root of Squared Array:", z_sqrt)  # [1., 2., 3., 4.]

# -----------------------------------------------
# 🚀 **Exponential and Logarithmic Functions**
# -----------------------------------------------
# Exponential (e^x) of each element in y
z_exp = np.exp(y)
print("\n🔹 Exponential (e^y):", z_exp)  # [e^1, e^2, e^3, e^4]

# Natural logarithm of z_exp
z_log = np.log(z_exp)
print("🔹 Natural Log (ln(e^y)):", z_log)  # [1., 2., 3., 4.]

# -----------------------------------------------
# 🚀 **Trigonometric Functions**
# -----------------------------------------------
# Sine of each element in x
z_sin = np.sin(x)
print("\n🔹 Sine of x (sin(x)):", z_sin)

# Cosine of each element in x
z_cos = np.cos(x)
print("🔹 Cosine of x (cos(x)):", z_cos)

# Tangent of each element in x
z_tan = np.tan(x)
print("🔹 Tangent of x (tan(x)):", z_tan)

# -----------------------------------------------
# 🚀 **Summary of Operations**
# -----------------------------------------------
# ✅ Addition, subtraction, multiplication, and division are applied element-wise.
# ✅ NumPy supports advanced mathematical functions like `sqrt`, `exp`, `log`, and trigonometric operations.
# ✅ Operations are vectorized for better performance compared to Python loops.

# -----------------------------------------------
# 🏋️‍♂️ **Practice Exercise**
# -----------------------------------------------
# 1️⃣ Create two arrays `a` and `b` with 5 random integers each.
# 2️⃣ Perform element-wise addition, subtraction, and multiplication on `a` and `b`.
# 3️⃣ Find the square root of the result of their multiplication.

# 🚀 Starter Code:
a = np.random.randint(1, 10, size=5)  # Random integers between 1 and 10
b = np.random.randint(1, 10, size=5)  # Random integers between 1 and 10
print("\n🔹 Array a:", a)
print("🔹 Array b:", b)

# Perform operations
sum_ab = a + b
diff_ab = a - b
prod_ab = a * b
sqrt_prod = np.sqrt(prod_ab)

print("\n🔹 Sum of a and b:", sum_ab)
print("🔹 Difference of a and b:", diff_ab)
print("🔹 Product of a and b:", prod_ab)
print("🔹 Square Root of Product:", sqrt_prod)


🔹 Array x: [1 2 3 4]
🔹 Array y: [1 2 3 4]

🔹 Addition (x + y): [2 4 6 8]

🔹 Subtraction (x - y): [0 0 0 0]
🔹 Multiplication (x * y): [ 1  4  9 16]
🔹 Division (x / y): [1. 1. 1. 1.]

🔹 Squared (x ** 2): [ 1  4  9 16]
🔹 Square Root of Squared Array: [1. 2. 3. 4.]

🔹 Exponential (e^y): [ 2.71828183  7.3890561  20.08553692 54.59815003]
🔹 Natural Log (ln(e^y)): [1. 2. 3. 4.]

🔹 Sine of x (sin(x)): [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
🔹 Cosine of x (cos(x)): [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
🔹 Tangent of x (tan(x)): [ 1.55740772 -2.18503986 -0.14254654  1.15782128]

🔹 Array a: [5 8 8 7 4]
🔹 Array b: [6 7 2 1 5]

🔹 Sum of a and b: [11 15 10  8  9]
🔹 Difference of a and b: [-1  1  6  6 -1]
🔹 Product of a and b: [30 56 16  7 20]
🔹 Square Root of Product: [5.47722558 7.48331477 4.         2.64575131 4.47213595]


# ELEMENTS SLICING AND INDEXING

In [22]:
# ELEMENTS SLICING AND INDEXING 🔪
# -----------------------------------------------
# NumPy allows for powerful and efficient ways to access and modify data using indexing and slicing.
# Let's explore how to access individual elements, slices of arrays, and even manipulate them.

import numpy as np

# -----------------------------------------------
# 🚀 **1D Array Indexing and Slicing**
# -----------------------------------------------
# Create a 1D array
x = np.random.randint(1, 10, 10)  # Random integers between 1 and 10
print("🔹 Array x:", x)

# Accessing individual elements
print("\n🔹 Accessing first element (x[0]):", x[0])  # First element
print("🔹 Accessing last element (x[-1]):", x[-1])  # Last element using negative index

# Slicing: Accessing a range of elements
print("\n🔹 Accessing first 3 elements (x[0:3]):", x[0:3])  # First 3 elements
print("🔹 Accessing all elements after index 3 (x[3:]):", x[3:])  # From index 3 to the end
print("🔹 Accessing elements with step 2 (x[::2]):", x[::2])  # Every second element

# -----------------------------------------------
# 🚀 **Broadcasting: Modify Elements in Bulk**
# -----------------------------------------------
# Change the first 3 elements to 10
x[0:3] = 10
print("\n🔹 Modified Array (x[0:3] = 10):", x)

# -----------------------------------------------
# 🚀 **2D Array Indexing and Slicing**
# -----------------------------------------------
# Create a 2D array (Matrix)
matrix = np.random.randint(1, 10, (5, 5))  # Random 5x5 matrix
print("\n🔹 2D Array (Matrix):\n", matrix)

# Access a specific row
print("\n🔹 Access row 2 (matrix[2]):", matrix[2])  # Row at index 2

# Access a specific element
print("🔹 Access element at row 0, column 2 (matrix[0, 2]):", matrix[0, 2])

# Slice rows and columns
mini_matrix = matrix[1:4, 1:4]  # Extract a submatrix (rows 1-3, columns 1-3)
print("\n🔹 Submatrix (matrix[1:4, 1:4]):\n", mini_matrix)

# -----------------------------------------------
# 🚀 **Advanced Slicing**
# -----------------------------------------------
# Extract all rows but only the first two columns
column_slice = matrix[:, :2]
print("\n🔹 First 2 Columns (matrix[:, :2]):\n", column_slice)

# Extract the last two rows
row_slice = matrix[-2:, :]
print("🔹 Last 2 Rows (matrix[-2:, :]):\n", row_slice)

# Use step slicing to skip rows/columns
stepped_matrix = matrix[::2, ::2]  # Every second row and column
print("🔹 Stepped Matrix (matrix[::2, ::2]):\n", stepped_matrix)

# -----------------------------------------------
# 🚀 **Boolean Indexing**
# -----------------------------------------------
# Boolean indexing allows filtering based on conditions
greater_than_five = matrix[matrix > 5]  # Extract elements > 5
print("\n🔹 Elements greater than 5 (matrix[matrix > 5]):", greater_than_five)

# Modify all elements greater than 5 to 99
matrix[matrix > 5] = 99
print("🔹 Modified Matrix (elements > 5 = 99):\n", matrix)

# -----------------------------------------------
# 🏋️‍♂️ **Practice Exercises**
# -----------------------------------------------
# 1️⃣ Create a random 1D array of size 15. Extract:
#     - The first 5 elements
#     - Every third element
#     - Elements between indices 5 and 10
#
# 2️⃣ Create a random 3x4 matrix. Perform the following:
#     - Extract the first column
#     - Extract the last two rows
#     - Replace all even numbers with -1
#
# 3️⃣ Given a 5x5 matrix, extract the diagonal elements.

# 🚀 Starter Code for Practice
array_1d = np.random.randint(1, 20, 15)  # Random 1D array
print("\n🔹 Practice Array (1D):", array_1d)

array_2d = np.random.randint(1, 20, (3, 4))  # Random 3x4 matrix
print("\n🔹 Practice Matrix (2D):\n", array_2d)

matrix_5x5 = np.random.randint(1, 20, (5, 5))  # Random 5x5 matrix
print("\n🔹 Practice Matrix (5x5):\n", matrix_5x5)

# -----------------------------------------------
# 💡 Summary
# -----------------------------------------------
# ✅ Indexing allows accessing specific elements or ranges within arrays.
# ✅ Slicing lets you extract subarrays efficiently.
# ✅ Boolean indexing is a powerful way to filter or modify arrays based on conditions.
# ✅ NumPy's slicing and indexing are fast and memory-efficient compared to Python lists.


🔹 Array x: [8 6 1 5 3 5 3 4 1 8]

🔹 Accessing first element (x[0]): 8
🔹 Accessing last element (x[-1]): 8

🔹 Accessing first 3 elements (x[0:3]): [8 6 1]
🔹 Accessing all elements after index 3 (x[3:]): [5 3 5 3 4 1 8]
🔹 Accessing elements with step 2 (x[::2]): [8 1 3 3 1]

🔹 Modified Array (x[0:3] = 10): [10 10 10  5  3  5  3  4  1  8]

🔹 2D Array (Matrix):
 [[8 5 9 4 2]
 [3 2 2 3 5]
 [9 7 8 7 3]
 [3 5 7 5 5]
 [4 6 6 3 9]]

🔹 Access row 2 (matrix[2]): [9 7 8 7 3]
🔹 Access element at row 0, column 2 (matrix[0, 2]): 9

🔹 Submatrix (matrix[1:4, 1:4]):
 [[2 2 3]
 [7 8 7]
 [5 7 5]]

🔹 First 2 Columns (matrix[:, :2]):
 [[8 5]
 [3 2]
 [9 7]
 [3 5]
 [4 6]]
🔹 Last 2 Rows (matrix[-2:, :]):
 [[3 5 7 5 5]
 [4 6 6 3 9]]
🔹 Stepped Matrix (matrix[::2, ::2]):
 [[8 9 2]
 [9 8 3]
 [4 6 9]]

🔹 Elements greater than 5 (matrix[matrix > 5]): [8 9 9 7 8 7 7 6 6 9]
🔹 Modified Matrix (elements > 5 = 99):
 [[99  5 99  4  2]
 [ 3  2  2  3  5]
 [99 99 99 99  3]
 [ 3  5 99  5  5]
 [ 4 99 99  3 99]]

🔹 Practice Arr

# ELEMENTS SELECTION

In [25]:
# ELEMENTS SELECTION 🧮
# -----------------------------------------------
# NumPy provides a robust way to select elements based on conditions, 
# also known as boolean indexing. This feature allows efficient filtering 
# and processing of arrays.

import numpy as np

# -----------------------------------------------
# 🚀 **Boolean Indexing**
# -----------------------------------------------
# Create a random 5x5 matrix with values from 1 to 10
matrix = np.random.randint(1, 10, (5, 5))  # 5x5 matrix
print("🔹 Original Matrix:\n", matrix)

# Select all elements greater than 3
new_matrix = matrix[matrix > 3]
print("\n🔹 Elements greater than 3:\n", new_matrix)

# Select all even elements (elements divisible by 2)
even_matrix = matrix[matrix % 2 == 0]
print("\n🔹 Even elements (matrix % 2 == 0):\n", even_matrix)

# Select all odd elements
odd_matrix = matrix[matrix % 2 != 0]
print("\n🔹 Odd elements (matrix % 2 != 0):\n", odd_matrix)

# -----------------------------------------------
# 🚀 **Combining Conditions**
# -----------------------------------------------
# Select elements greater than 3 and less than 8
filtered_matrix = matrix[(matrix > 3) & (matrix < 8)]
print("\n🔹 Elements between 3 and 8:\n", filtered_matrix)

# Select elements that are either less than 4 or equal to 9
complex_condition = matrix[(matrix < 4) | (matrix == 9)]
print("\n🔹 Elements < 4 or == 9:\n", complex_condition)

# -----------------------------------------------
# 🚀 **Modify Elements Using Conditions**
# -----------------------------------------------
# Replace all elements greater than 5 with 99
matrix[matrix > 5] = 99
print("\n🔹 Matrix after replacing elements > 5 with 99:\n", matrix)

# Replace all even numbers with -1
matrix[matrix % 2 == 0] = -1
print("\n🔹 Matrix after replacing even numbers with -1:\n", matrix)

# -----------------------------------------------
# 🏋️‍♂️ **Practice Exercises**
# -----------------------------------------------
# 1️⃣ Create a 6x6 random matrix and extract:
#     - All elements greater than 7.
#     - All elements divisible by 3.
#     - Replace all elements less than 5 with 0.

# 2️⃣ Combine conditions:
#     - Extract elements greater than 2 but less than 8.
#     - Replace all odd elements with 77.

# 🚀 Starter Code for Practice
practice_matrix = np.random.randint(1, 15, (6, 6))
print("\n🔹 Practice Matrix:\n", practice_matrix)

# -----------------------------------------------
# 💡 Summary
# -----------------------------------------------
# ✅ Boolean indexing allows you to filter and extract elements based on conditions.
# ✅ You can combine multiple conditions using logical operators (`&`, `|`).
# ✅ Boolean indexing is efficient and widely used in data processing workflows.
# ✅ Practice modifying and filtering data to strengthen your understanding!


🔹 Original Matrix:
 [[4 2 3 5 7]
 [1 2 8 4 2]
 [9 8 7 7 9]
 [3 4 6 3 3]
 [4 9 2 4 5]]

🔹 Elements greater than 3:
 [4 5 7 8 4 9 8 7 7 9 4 6 4 9 4 5]

🔹 Even elements (matrix % 2 == 0):
 [4 2 2 8 4 2 8 4 6 4 2 4]

🔹 Odd elements (matrix % 2 != 0):
 [3 5 7 1 9 7 7 9 3 3 3 9 5]

🔹 Elements between 3 and 8:
 [4 5 7 4 7 7 4 6 4 4 5]

🔹 Elements < 4 or == 9:
 [2 3 1 2 2 9 9 3 3 3 9 2]

🔹 Matrix after replacing elements > 5 with 99:
 [[ 4  2  3  5 99]
 [ 1  2 99  4  2]
 [99 99 99 99 99]
 [ 3  4 99  3  3]
 [ 4 99  2  4  5]]

🔹 Matrix after replacing even numbers with -1:
 [[-1 -1  3  5 99]
 [ 1 -1 99 -1 -1]
 [99 99 99 99 99]
 [ 3 -1 99  3  3]
 [-1 99 -1 -1  5]]

🔹 Practice Matrix:
 [[ 3  7  5  2  5 11]
 [ 5  8  5 13  5  5]
 [13  3  5  5  3  4]
 [12 12  4 11  3 10]
 [ 2  8  2  2  4  8]
 [ 5 10 13 14 13  1]]


# NOW YOU HAVE MASTERED NUMPY, GIVE YOURSELF A PAT ON THE SHOULDER!